### ISSUE TITLE
i have problem when run tool 

### ISSUE THREAD

**Issue by shadihh9** [Ebryx/GitDump#4]
when run tool 
URL for test: https://www.soom.com/.git/
Fetching: https://www.soom.com/.git/index
Fetching: https://www.soom.com/.git/FETCH_HEAD
Fetching: https://www.soom.com/.git/HEAD
Fetching: https://www.soom.com/.git/ORIG_HEAD
Fetching: https://www.soom.com/.git/config
Fetching: https://www.soom.com/.git/description
Fetching: https://www.soom.com/.git/packed-refs
Fetching: https://www.soom.com/.git/info/exclude
Fetching: https://www.soom.com/.git/info/refs
Fetching: https://www.soom.com/.git/logs/HEAD
Fetching: https://www.soom.com/.git/logs/refs/heads/develop
Fetching: https://www.soom.com/.git/logs/refs/heads/master
Fetching: https://www.soom.com/.git/logs/refs/remotes/origin/develop
Fetching: https://www.soom.com/.git/logs/refs/remotes/origin/step_develop
Fetching: https://www.soom.com/.git/logs/refs/remotes/origin/master
Fetching: https://www.soom.com/.git/logs/refs/remotes/github/master
Fetching: https://www.soom.com/.git/refs/heads/develop
Fetching: https://www.soom.com/.git/refs/heads/master
Fetching: https://www.soom.com/.git/refs/remotes/origin/develop
Fetching: https://www.soom.com/.git/refs/remotes/origin/master
Fetching: https://www.soom.com/.git/refs/remotes/origin/step_develop
Fetching: https://www.soom.com/.git/refs/remotes/github/master
Fetching: https://www.soom.com/.git/objects/info/packs
Fetching: https://www.soom.com/.git/refs/remotes/origin/HEAD
Parsing Index File
Traceback (most recent call last):
  File "git-dump.py", line 250, in <module>
    main()
  File "git-dump.py", line 243, in main
    gitDumper()
  File "git-dump.py", line 201, in gitDumper
    sha1List = sha1Extractor()
  File "git-dump.py", line 113, in sha1Extractor
    jsonList = gin.parse_file(outputFolder + ".git/index", pretty=False)
  File "/root/GitDump/gin.py", line 179, in parse_file
    for item in parse(arg, pretty=pretty):
  File "/root/GitDump/gin.py", line 27, in parse
    with open(filename, "rb") as o:
FileNotFoundError: [Errno 2] No such file or directory: 'output/.git/index'

**Comment by ftameznubetia** [comment]
same for me... find any solution?

**Comment by anastasiaxx** [comment]
same for me
